version: '3.8'
name: spirling

services:
  spirling_php82:
    container_name: spirling_php82
    build:
      context: ./services/php/8.2
      args:
      - INSTALL_XDEBUG=${INSTALL_XDEBUG}
      - SERVER_NAME=${SERVER_NAME}
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
    restart: always
    depends_on:
      - spirling_mysql
    links:
      - spirling_mysql
    environment:
      PHP_IDE_CONFIG: "serverName=${SERVER_NAME}"
    volumes:
      - "$WEB_ROOT:/var/www"
      - ./config/php/8.2/php.ini:/usr/local/etc/php/php.ini
    extra_hosts:
      - host.docker.internal:host-gateway

  spirling_php74:
    container_name: spirling_php74
    build:
      context: ./services/php/7.4
      args:
      - INSTALL_XDEBUG=${INSTALL_XDEBUG}
      - SERVER_NAME=${SERVER_NAME}
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
    restart: always
    depends_on:
      - spirling_mysql
    links:
      - spirling_mysql
    environment:
      PHP_IDE_CONFIG: "serverName=${SERVER_NAME}"
    volumes:
      - "$WEB_ROOT:/var/www"
    extra_hosts:
      - host.docker.internal:host-gateway

  spirling_nginx:
    container_name: spirling_nginx
    image: nginx
    restart: always
    ports:
      - "88:80"
      - "1443:443"
    volumes:
      - "./config/nginx:/etc/nginx/conf.d"
      - "./config/ssl:/etc/nginx/ssl"
      - "${WEB_ROOT}:/var/www"
      - "./var/log/nginx:/var/log/nginx"
    depends_on:
      - spirling_php82

  spirling_mysql:
    container_name: spirling_mysql
    image: mysql:8.0
    restart: always
    volumes:
      - "./data/mysql:/var/lib/mysql"
      - "./var/logs/mysql:/var/log/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Europe/Kiev
    ports:
      - "3310:3306"